#include <iostream>

using namespace std;

int main()

{
    /* Polymorphism:-
       - one name and multiple forms.
       - eg. Function Overloading, Operator Overloading.
       - eg. Vitual Functions.
       Polymorphism in C++ can be of two types:-
       1. Compile Time Polymorphism:-
          Compile Time Polymorphism in C++ can be achieved using:-
          1.1 - Function Overloading.
          1.2 - Operator Overloading.
       2. Run Time Polymorphism:-
          Run Time Polymorphism in C++ can be achieved using:-
          2.1 - Virtual Functions.
    */
    return 0;
}