#include <iostream>

using namespace std;

int main()
{
    //**************************-:Build in Data Types:-********************************
    // int a, b, c;
    // cout << "Enter the value of a:" << endl;
    // cin >> a;
    // cout << "Enter the value of b:" << endl;
    // cin >> b;
    // c = a + b;
    // cout << "The sum of a and b is: " << c << endl;

    // // **************************-:float, double and long double literals:-**********************
    // float d = 45.6f; // C++ compiler will show the point as double, by writting f and l in the value will become float and long double:-
    // long double e = 45.7l;
    // cout << "The value of a is " << d << endl;
    // cout << "The value of b is " << e << endl;
    // cout << "The size of a in double is " << sizeof(45.6) << endl;
    // cout << "The size of a in float is " << sizeof(45.6f) << endl;
    // cout << "The size of a in long double is " << sizeof(45.6l) << endl;
    // cout << endl;

    // //**************************-:Reference Variables:-***********************************
    // Name(Rohan Das)--->Father(Monty)--->Friend(Rohu)--->Itself(Dangerous_Coder):-
    // float x = 50;
    // float &y = x;
    // cout << x << endl;
    // cout << y << endl;
    // cout << endl;

    //**************************-:Type Casting:-***********************************
    // int m = 35;
    // float n = 35.45;
    // cout << "The value of 'a' from integer to floating point is " << float(m) << endl;
    // cout << "The value of 'b' from floating point to integer is " << int(n) << endl;

    // cout << "The value of expression is " << m + n << endl;
    // cout << "The value of expression is " << m + (int)n << endl;
    // cout << "The value of expression is " << m + int(n) << endl;
    return 0;
}