#include <iostream>

using namespace std;

int main()
{
    int i = 0;
    //-:Types of Loops:-
    //For Loop
    //While Loop
    //do-while Loop

    //For Loop:-
    // for (int i = 0; i < 10; i++)
    // {
    //     cout << i + 1 << endl;
    // }
    
    //While loop:-
    // while (i < 40)
    // {
    //     cout << i + 1 << endl;
    //     i++;
    // }

    //Infinite While loop:-
    // while (true)
    // {
    //     cout << i + 1 << endl;
    //     i++;
    // }

    //Do-while loop:-
    // do
    // {
    //     cout << i + 1 << endl;
    //     i++;
    // } while (i < 40);
    
    return 0;
}